import { ApplicationStatus, ReviewStatus, UserRole } from "@prisma/client";
import jwt from "jsonwebtoken";
import request from "supertest";
import { beforeEach, describe, expect, it, vi } from "vitest";

const db = vi.hoisted(() => ({ reviewerAssignment: { findUnique: vi.fn() }, review: { findUnique: vi.fn(), create: vi.fn(), update: vi.fn() }, conflictOfInterest: { findFirst: vi.fn(), create: vi.fn() }, application: { update: vi.fn() }, auditEvent: { create: vi.fn() }, $transaction: vi.fn() }));
vi.mock("../src/config/prisma.js", () => ({ prisma: db }));
import { app } from "../src/app.js";

const secret = "test-jwt-secret-that-is-long-enough-for-validation";
const reviewer = { id: "reviewer-1", role: UserRole.REVIEWER };
const other = { id: "reviewer-2", role: UserRole.REVIEWER };
const po = { id: "officer-1", role: UserRole.PROGRAM_OFFICER };
const token = (user: typeof reviewer | typeof po) => jwt.sign({ userId: user.id, role: user.role }, secret);
const headers = { Authorization: `Bearer ${token(reviewer)}` };
const reviewInput = { impactScore: 4, comments: " Promising impact. " };
function assignment(overrides: Record<string, unknown> = {}) { return { id: "assignment-1", applicationId: "application-1", reviewerId: reviewer.id, removedAt: null, application: { id: "application-1", archivedAt: null, status: ApplicationStatus.ASSIGNED }, review: null, ...overrides }; }
function review(overrides: Record<string, unknown> = {}) { return { id: "review-1", assignmentId: "assignment-1", applicationId: "application-1", reviewerId: reviewer.id, status: ReviewStatus.DRAFT, impactScore: 4, feasibilityScore: 3, budgetJustificationScore: 5, comments: "Promising impact.", completedAt: null, assignment: assignment(), ...overrides }; }

describe("review workflow", () => {
  beforeEach(() => { for (const group of Object.values(db)) { if (typeof group === "function") group.mockReset(); else for (const fn of Object.values(group as object)) if (typeof fn === "function") (fn as ReturnType<typeof vi.fn>).mockReset(); } db.reviewerAssignment.findUnique.mockResolvedValue(assignment()); db.review.findUnique.mockResolvedValue(review()); db.conflictOfInterest.findFirst.mockResolvedValue(null); db.conflictOfInterest.create.mockImplementation(async ({ data }: { data: object }) => ({ id: "conflict-1", ...data })); db.review.create.mockImplementation(async ({ data }: { data: object }) => review(data)); db.review.update.mockImplementation(async ({ data }: { data: object }) => review(data)); db.$transaction.mockImplementation(async (callback: (tx: typeof db) => unknown) => callback(db)); });
  it("requires authenticated Reviewers to create drafts", async () => { expect((await request(app).post("/assignments/assignment-1/review").send({})).status).toBe(401); expect((await request(app).post("/assignments/assignment-1/review").set("Authorization", `Bearer ${token(po)}`).send({})).status).toBe(403); });
  it("creates partial drafts, transitions ASSIGNED, and audits both writes", async () => { const response = await request(app).post("/assignments/assignment-1/review").set(headers).send(reviewInput); expect(response).toMatchObject({ status: 201, body: { review: { status: "DRAFT", impactScore: 4, comments: "Promising impact." } } }); expect(db.application.update).toHaveBeenCalledWith(expect.objectContaining({ data: { status: "UNDER_REVIEW" } })); expect(db.auditEvent.create).toHaveBeenCalledTimes(2); });
  it("rejects cross-reviewer, removed, archived, decided, duplicate, and conflicted drafts", async () => { db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ reviewerId: other.id })); const foreign = await request(app).post("/assignments/assignment-1/review").set(headers).send({}); db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ removedAt: new Date() })); const removed = await request(app).post("/assignments/assignment-1/review").set(headers).send({}); db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ application: { archivedAt: new Date(), status: ApplicationStatus.ASSIGNED } })); const archived = await request(app).post("/assignments/assignment-1/review").set(headers).send({}); db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ application: { archivedAt: null, status: ApplicationStatus.DECIDED } })); const decided = await request(app).post("/assignments/assignment-1/review").set(headers).send({}); db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ review: review() })); const duplicate = await request(app).post("/assignments/assignment-1/review").set(headers).send({}); db.conflictOfInterest.findFirst.mockResolvedValueOnce({ id: "conflict" }); const conflict = await request(app).post("/assignments/assignment-1/review").set(headers).send({}); expect([foreign.status, removed.status, archived.status, decided.status, duplicate.status, conflict.status]).toEqual([403,409,409,409,409,409]); });
  it("validates every supplied score as an integer from one to five", async () => { for (const body of [{ impactScore: 0 }, { feasibilityScore: 6 }, { budgetJustificationScore: 1.5 }, { impactScore: "4" }]) expect((await request(app).post("/assignments/assignment-1/review").set(headers).send(body)).status).toBe(400); });
  it("updates drafts but locks completed or conflicted reviews", async () => { const edited = await request(app).patch("/reviews/review-1").set(headers).send({ comments: "Updated" }); db.review.findUnique.mockResolvedValueOnce(review({ status: ReviewStatus.COMPLETED })); const completed = await request(app).patch("/reviews/review-1").set(headers).send({ comments: "No" }); db.conflictOfInterest.findFirst.mockResolvedValueOnce({ id: "conflict" }); const conflicted = await request(app).patch("/reviews/review-1").set(headers).send({ comments: "No" }); expect(edited.status).toBe(200); expect([completed.status, conflicted.status]).toEqual([409,409]); });
  it("completes only fully scored drafts and declares conflicts with a reason", async () => { const complete = await request(app).post("/reviews/review-1/complete").set(headers); db.review.findUnique.mockResolvedValueOnce(review({ impactScore: null })); const incomplete = await request(app).post("/reviews/review-1/complete").set(headers); const declaration = await request(app).post("/assignments/assignment-1/conflict").set(headers).send({ reason: " Prior relationship " }); expect(complete.status).toBe(200); expect(incomplete.status).toBe(409); expect(declaration.status).toBe(201); expect(db.conflictOfInterest.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ reason: "Prior relationship" }) })); });
  it("retrieves owned drafts and completed reviews but never leaks another Reviewer's review", async () => { db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ review: review() })); const draft = await request(app).get("/assignments/assignment-1/review").set(headers); db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ review: review({ status: ReviewStatus.COMPLETED, completedAt: new Date("2026-10-01") }) })); const completed = await request(app).get("/assignments/assignment-1/review").set(headers); db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ reviewerId: other.id, review: review({ reviewerId: other.id }) })); const foreign = await request(app).get("/assignments/assignment-1/review").set(headers); expect(draft).toMatchObject({ status: 200, body: { review: { status: "DRAFT", impactScore: 4 } } }); expect(completed).toMatchObject({ status: 200, body: { review: { status: "COMPLETED", completedAt: "2026-10-01T00:00:00.000Z" } } }); expect(foreign.status).toBe(403); expect(foreign.body.review).toBeUndefined(); });
  it("blocks foreign, removed, archived, and decided draft mutations without writes", async () => { for (const state of [assignment({ reviewerId: other.id }), assignment({ removedAt: new Date() }), assignment({ application: { archivedAt: new Date(), status: ApplicationStatus.ASSIGNED } }), assignment({ application: { archivedAt: null, status: ApplicationStatus.DECIDED } })]) { db.reviewerAssignment.findUnique.mockResolvedValueOnce(state); const edit = await request(app).patch("/reviews/review-1").set(headers).send({ comments: "No" }); db.reviewerAssignment.findUnique.mockResolvedValueOnce(state); const complete = await request(app).post("/reviews/review-1/complete").set(headers); expect([edit.status, complete.status]).toEqual(state.reviewerId === other.id ? [403,403] : [409,409]); } expect(db.review.update).not.toHaveBeenCalled(); expect(db.auditEvent.create).not.toHaveBeenCalled(); });
  it("blocks conflict declaration after completion and creates a distinct reassignment review", async () => { db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ review: review({ status: ReviewStatus.COMPLETED }) })); const conflict = await request(app).post("/assignments/assignment-1/conflict").set(headers).send({ reason: "Relationship" }); expect(conflict.status).toBe(409); expect(db.conflictOfInterest.create).not.toHaveBeenCalled(); const historical = review({ id: "review-old", assignmentId: "assignment-old" }); db.reviewerAssignment.findUnique.mockResolvedValueOnce(assignment({ id: "assignment-new", review: null })); const reassigned = await request(app).post("/assignments/assignment-new/review").set(headers).send({ impactScore: 5 }); expect(reassigned).toMatchObject({ status: 201, body: { review: { assignmentId: "assignment-new" } } }); expect(historical).toMatchObject({ assignmentId: "assignment-old", id: "review-old" }); });
});
